[build]
command = "npm run build"
publish = "client/dist"
functions = "api/build"
base = "/"

[dev]
command = "npm run start"
functionsPort = 9000
targetPort = 4200
port = 8080
envFiles = [".env.development.local", ".env.local", ".env.development", ".env"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200