name: Continuous Deployment

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'

jobs:
  process:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Cache
      uses: actions/cache@v3
      id: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}

    - name: Install Dependencies
      run: npm install
      if: steps.cache-npm.outputs.cache-hit != 'true'

    - name: Build
      run: npm run build --if-present

    - name: Deploy
      run: netlify deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}